### ISSUE TITLE
coppy&edit: 1

### ISSUE THREAD

**Issue by 70198907** [mozilla/extension-workshop#1903]
### Anything else we should know?

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/extension-workshop/pull/1902
- [ ] https://github.com/mozilla/extension-workshop/pull/1901
- [ ] https://github.com/mozilla/extension-workshop/pull/1897
- [ ] https://github.com/mozilla/extension-workshop/pull/1898
```
