### ISSUE TITLE
[Tracking issue] The extension workshop contains many links that are 404 -ing

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/extension-workshop#245]
### Note
This issue has been edited to reflect the updated Information Architecture (IA) of the site. 

### Describe the problem and steps to reproduce it:

Open the following resources:

I. [**Homepage**](https://extensionworkshop-dev.allizom.org/)
Under "Ready to build an extension for Firefox?"
![image](https://user-images.githubusercontent.com/31961530/61933594-ec870800-af8e-11e9-8fd8-8564169af9c4.png)
- [x] - All the above resources point to https://extensionworkshop-dev.allizom.org/documentation/develop/web-ext-webpack-plug-in/ , which is a 404

II. [**Documentation Topics - Develop**](https://extensionworkshop-dev.allizom.org/documentation/develop/)
All the links mentioned below are 404 - ing

**`Getting started`** section in the left side panel
- [x] - https://extensionworkshop-dev.allizom.org/documentation/develop/firefox-workflow-overview/ 
- [x] - https://extensionworkshop-dev.allizom.org/documentation/develop/about-the-webextensions-api/

**`Mobile`** section in the left side panel
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/geckoview-extensions-android-library/~~ - relocated at https://github.com/mozilla/geckoview
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/desktop-and-android-differences/~~ - relocated at https://extensionworkshop-dev.allizom.org/documentation/develop/differences-between-desktop-and-android-extensions/
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/developing-for-firefox-for-android/~~ - relocated at https://extensionworkshop-dev.allizom.org/documentation/develop/developing-extensions-for-firefox-for-android/

**`Port Your Extension`** section in the left side panel
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/port-chrome-extension/~~ - relocated at https://extensionworkshop-dev.allizom.org/documentation/develop/porting-a-google-chrome-extension/
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/legacy-firefox-extension/~~ - relocated at https://extensionworkshop-dev.allizom.org/documentation/develop/porting-a-legacy-firefox-extension/
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/add-on-sdk/~~ - relocated at https://extensionworkshop-dev.allizom.org/documentation/develop/comparison-with-the-add-on-sdk/
- [x] - ~~https://extensionworkshop-dev.allizom.org/documentation/develop/xul-xpcom-comparison/~~ - relocated at https://extensionworkshop-dev.allizom.org/documentation/develop/comparison-with-xul-xpcom-extensions/

**`Debug and Test`** section in the left side panel
- [x] - https://extensionworkshop-dev.allizom.org/documentation/develop/temporary-installation-in-firefox/
- [x] - https://extensionworkshop-dev.allizom.org/documentation/develop/debugging/
- [x] - https://extensionworkshop-dev.allizom.org/documentation/develop/testing-persistent-and-restart-features/
- [x] - https://extensionworkshop-dev.allizom.org/documentation/develop/test-permission-requests/

**Links in submenus on the Develop page**

 **`User experience - Build a secure extension`**
 - `Ensure you insert remote content safely` section
   - [x]  - ~~https://extensionworkshop-dev.allizom.org/en-US/docs/Web/API/Document/createElement~~ - redirects to MDN
   - [x]  - ~~https://extensionworkshop-dev.allizom.org/en-US/docs/Web/API/Element/setAttribute~~ - redirects to MDN
   - [x]  - ~~https://extensionworkshop-dev.allizom.org/en-US/docs/Web/API/Node/textContent~~ - redirects to MDN

- `Create your UI with extension components` section
   - [x]  - `built-in extension UI features` - ~~https://extensionworkshop-dev.allizom.org/en-US/Add-ons/WebExtensions/user_interface~~ - redirects to MDN
   - [x]  - `data URLs` - ~~https://extensionworkshop-dev.allizom.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs~~ - redirects to MDN

- `Don’t inject moz-extension paths directly` section
   - [x]  - ` data URLs` - ~~https://extensionworkshop-dev.allizom.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs~~ - redirects to MDN
   - [x]  - `srcdoc` - ~~https://extensionworkshop-dev.allizom.org/en-US/docs/Web/HTML/Element/iframe#attr-srcdoc~~ - redirects to MDN

III. [**Community**](https://extensionworkshop-dev.allizom.org/community/)
**`Contribute to the API`** section in the left side panel
- [x] ~~https://extensionworkshop-dev.allizom.org/community/api-overview/~~ - link no longer present

### What happened?
All the links mentioned are 404s

### What did you expect to happen?
The corresponding content should be loaded when these links are opened

### Anything else we should know?
@caitmuenster here is the list with all the links that are currently 404s (hope I didn't miss some of them, since they are quite a lot)

**Comment by mahimas28** [comment]
Hey can i take up this bug?

**Comment by caitmuenster** [comment]
Hey @mahimas28, we're still working on building out site pages so this probably isn't a good bug to work on. We'll probably have more issues coming in that require links to be updated, though, if you want to keep an eye on this repo!

**Comment by caitmuenster** [comment]
@AlexandraMoga You are a rock star for listing out the 404s. ⭐️ I am going to break the remaining 404s into separate issues to help make this a little bit more manageable and make this the master tracker issue for 404s.

**Comment by AlexandraMoga** [comment]
@caitmuenster It seems that all the links mentioned above are opening a corresponding resource now.

However, while checking the contents of the Documentation pages, I've run into a few other 404s:

- [ ] - [**Porting a legacy Firefox extension**](https://extensionworkshop-dev.allizom.org/documentation/develop/porting-a-legacy-firefox-extension/)
  - the `build a basic example` link in the Quick start section pointing to https://extensionworkshop-dev.allizom.org/documentation/develop/your-first-extension

![image](https://user-images.githubusercontent.com/31961530/65425464-b4793580-de16-11e9-90de-a9da4d45923e.png)

------------

- [ ] - **Publish - Recommended extensions**
  - https://extensionworkshop-dev.allizom.org/documentation/publish/recommended-extensions - but I think this one is already handled in https://github.com/mozilla/extension-workshop/pull/411

-----------

- [ ] - [**Enterprise distribution**](https://extensionworkshop-dev.allizom.org/documentation/enterprise/enterprise-distribution/#firefox-settings)
  - Firefox settings section - on a yellow note, there is a `this page` link pointing to https://extensionworkshop-dev.allizom.org/documentation/enterprise/enterprise-distribution/www.favbrowser.com/how-to-create-a-new-default-firefox-experience-in-your-enterprise/

![image](https://user-images.githubusercontent.com/31961530/65426374-ccea4f80-de18-11e9-9183-afa714818661.png)

------------

- [ ] - [**Using the AMO theme generator**](https://extensionworkshop-dev.allizom.org/documentation/themes/using-the-amo-theme-generator/#getting-started)
  - Getting started section - on a yellow note, there is a `Theme concepts` link which points to https://extensionworkshop-dev.allizom.org/documentation/publish/theme-concepts

![image](https://user-images.githubusercontent.com/31961530/65426776-93feaa80-de19-11e9-89e5-54a84b323d7b.png)

**Comment by caitmuenster** [comment]
Thanks @AlexandraMoga! I'll get some PRs up shortly.

**Comment by AlexandraMoga** [comment]
All links, except for the Recommended extensions one, are now working.

**Comment by muffinresearch** [comment]
> All links, except for the Recommended extensions one, are now working.

This is fixed now, it was missing a trailing slash in the config. See https://extensionworkshop-dev.allizom.org/documentation/publish/recommended-extensions

**Comment by AlexandraMoga** [comment]
The Recommended extensions page is available now.

Marking this issue as verified fixed.
